//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Question.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyQuestionEntities : DbContext
    {
        public SurveyQuestionEntities()
            : base("name=SurveyQuestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCheckAbleItem> TCheckAbleItems { get; set; }
        public virtual DbSet<TQuestionType> TQuestionTypes { get; set; }
        public virtual DbSet<TSurveyQuestion> TSurveyQuestions { get; set; }
        public virtual DbSet<TSurvey> TSurveys { get; set; }
        public virtual DbSet<TUser> TUsers { get; set; }
    }
}
