//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Question.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCheckAbleItem
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsVertical { get; set; }
        public byte DisplayOrder { get; set; }
        public int SurveyQuestionId { get; set; }
    
        public virtual TQuestionType TQuestionType { get; set; }
    }
}
