//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Common.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSurveyQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSurveyQuestion()
        {
            this.TCheckAbleItems = new HashSet<TCheckAbleItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int QuestionTypeId { get; set; }
        public System.DateTime RegisterMoment { get; set; }
        public int DisplayOrder { get; set; }
        public int SurveyId { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCheckAbleItem> TCheckAbleItems { get; set; }
        public virtual TSurvey TSurvey { get; set; }
    }
}
